apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react-weather-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-weather-app
  template:
    metadata:
      labels:
        app: react-weather-app
    spec:
      containers:
      - name: react-container
        image: priyam14/react-weather-app
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

